---
eccube_site_name: "rednails"
eccube_domain: "rednails.local"

# Database configuration
database_hostname: "127.0.0.1"
database_port: 23306
database_name: "eccube"
database_user: "dbuser"
database_password: "secret"

# Git configuration
git_username: "git-user"
git_email: "git-user@exampl.com"
project_root: "/var/www/{{ eccube_site_name }}"
base_code_repo: "ar-system@ar-system.git.backlog.com:/REDNAILS_EC/eccube.git"
git_branch: "dev"

# Docker configuration
docker_compose_version: "v2.36.2"

# Composer configuration
ansible_user_dir: "{{ ansible_env.HOME }}"
composer_version: "2"
composer_auth: {}

# Yarn configuration
yarn_version: "latest"
yarn_packages: []

# Plugin configuration
ace_client_api_url: "https://155.248.172.151:20443/dev"
