parameters:
  soap_xml_serializer:
    xmlns: "http://ar-system-api.co.jp/"
    default_serialize_options:
      - xml_format_output: true
      - xml_encoding: utf-8
      - encoder_ignored_node_types: 
        - \XML_PI_NODE
