# Author: Ars-Thong
parameters:
    http_client:
        default:
            base_uri: 'http://ar-system-api.co.jp/'
            options:
                timeout: 600
                verify: false
                headers:
                    'Content-Type': 'application/xml'
                    'Accept': 'application/xml'
                    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'
        overrides:
        # Change here for specific class
        # Example:
        # - Plugin\AceClient\AceServices\Model\Request\Jyuden\AddCart\OrderPrmModel:
        #     options:
        #         timeout: 60
        #         verify: true
        #         headers:
        #             'Content-Type': 'application/json'
        #             'Accept': 'application/json'
        

    prm_otd_format:
        default: 
            format: 'xml'
            options: 
                xml_format_output: true
                xml_encoding: 'Shift_JIS'

        overrides:
        # Change here for specific class
        # Example:
        # - Plugin\AceClient\AceServices\Model\Request\Jyuden\AddCart\OrderPrmModel:
        #     format: 'object'
        #     options:
        #         xml_format_output: true
        #         xml_encoding: 'utf-8'
        #         encoder_ignored_node_types:
        #             - \XML_PI_NODE

    soap_xml_serializer:
        xmlns: 
            '@xmlns': "http://ar-system-api.co.jp/"
        default_serialize_options:
            xml_format_output: true
            xml_encoding: 'utf-8'
            encoder_ignored_node_types: 
                - \XML_PI_NODE
        request_soap_header: '<?xml version="1.0" encoding="utf-8"?>
                                <soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
                                <soap12:Body>'
        request_soap_end: '</soap12:Body>
                            </soap12:Envelope>'

