# Author: Ars-Thong
parameters:
    ace_method:
        default:
            serializer: 
                class_name: 'Plugin\AceClient\AceServices\Model\Request\Jyuden\AddCart\Serializer'
            normalizer: 
                class_name: 'Plugin\AceClient\AceServices\Model\Response\Jyuden\AddCart\Normalizer'
            logger: 
                class_name: 'Plugin\AceClient\AceServices\Model\Logger\AceLogger'
            api_client:
                client_name: 'Plugin\AceClient\ApiClient\Api\Client\PostClient'
                base_uri: 'http://192.168.0.77:20443/ACEXML/'
                headers:
                    'Content-Type': 'application/soap+xml; charset=utf-8'
                    'User-Agent': 'AceClient v1.0'
                options:
                    timeout: 600
                    verify: false

        overrides:
            # Change here for overriding default configuration
            # Example:
            - Plugin\AceClient\Config\Model\TestLoadConfig:
                serializer: 
                    class_name: 'Test\Serializer'
                normalizer: 
                    # class_name: 'Test\Normalizer'
                logger: 
                    class_name: 
                api_client:
                    client_name: 'Plugin\AceClient\ApiClient\Api\Client\PostSoapClient'
                    base_uri: 'http://192.168.0.77:20443/testACEXML/'
                    headers:
                        'Content-Type': 'application/json'
                        'User-Agent': 'AceClient v1.2'
                    options:
                        timeout: 20
                        verify: true

    prm_otd_format:
        default: 
            format: 'xml'
            options: 
                xml_format_output: true
                xml_encoding: 'Shift_JIS'

        overrides:
        # Change here for overriding default configuration
        # Example:
        # - Plugin\AceClient\AceServices\Model\Request\Jyuden\AddCart\OrderPrmModel:
        #     format: 'object'
            # options:
            #     xml_format_output: true
            #     xml_encoding: 'utf-8'
            #     encoder_ignored_node_types:
            #         - \XML_PI_NODE

    soap_xml_serializer:
        xmlns: 
            '@xmlns': "http://ar-system-api.co.jp/"
        default_serialize_options:
            xml_format_output: true
            xml_encoding: 'utf-8'
            encoder_ignored_node_types: 
                - \XML_PI_NODE
        request_soap_head: '<?xml version="1.0" encoding="utf-8"?>
                                <soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
                                <soap12:Body>'
        request_soap_end: '</soap12:Body>
                            </soap12:Envelope>'

