services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Plugin\AceClient43\Util\Logger\SoapXmlLogger:
        calls:
            - setLogger: ['@monolog.logger']
            - setFrontLogger: ['@monolog.logger.front']
            - setAdminLogger: ['@monolog.logger.admin']
            - setContext: ['@Eccube\Request\Context']

    Plugin\AceClient43\Security\Authenticator\CustomerAuthenticator:
        arguments:
            $innerAuthenticator: '@security.authenticator.form_login.customer'
            $router: '@router'
            $configRepository: '@Plugin\AceClient43\Repository\ConfigRepository'
            $customerRepository: '@Eccube\Repository\CustomerRepository'
            $customerBridge: '@Plugin\AceClient43\Bridge\CustomerBridge'
            $logger: '@monolog.logger.front'

    Plugin\AceClient43\Util\Logger\LoggerProvider:
        arguments:
            - '@Plugin\AceClient43\Util\Logger\SoapXmlLogger'

    Plugin\AceClient43\Service\ChargeProcessor:
        tags:
            - { name: eccube.item.holder.preprocessor, flow_type: shopping, priority: 550 }

    Plugin\AceClient43\Service\DeliveryFeeProcessor:
        tags:
            - { name: eccube.item.holder.preprocessor, flow_type: shopping, priority: 750 }

    Plugin\AceClient43\Service\DiscountProcessor:
        tags:
          - { name: eccube.discount.processor, flow_type: shopping, priority: 950 }


    Plugin\AceClient43\Service\Decorators\ProductClassComparator:
        decorates: Eccube\Service\Cart\ProductClassComparator
        decoration_priority: 10

    Plugin\AceClient43\Service\Decorators\CartService:
        decorates: Eccube\Service\CartService
        arguments:
            $cartItemComparator: '@Plugin\AceClient43\Service\Decorators\ProductClassComparator'
        decoration_priority: 10

    Plugin\AceClient43\Service\Decorators\OrderHelper:
        decorates: Eccube\Service\OrderHelper
        decoration_priority: 10

security:
    firewalls:
        customer:
            custom_authenticators:
                - Plugin\AceClient43\Security\Authenticator\CustomerAuthenticator
            entry_point: Plugin\AceClient43\Security\Authenticator\CustomerAuthenticator
