<?php

namespace Plugin\AceClient43\Repository;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Entity\CustomerAddress;
use Eccube\Entity\Shipping;
use Eccube\Repository\CustomerAddressRepository as BaseRepository;

/**
 * CustomerAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerAddressRepository extends BaseRepository
{
    /**
     * CustomerAddressRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry);
    }

    /**
     * お届け先を削除します.
     *
     * @param CustomerAddress $CustomerAddress
     */
    public function delete($CustomerAddress)
    {
        $em = $this->getEntityManager();

        // Use a transaction to ensure data consistency
        $em->beginTransaction();

        try {
            // First, update all related Shipping entities to set customer_address to null
            $em->createQueryBuilder()
                ->update(Shipping::class, 's')
                ->set('s.customer_address', ':null')
                ->where('s.customer_address = :customerAddress')
                ->setParameter('null', null)
                ->setParameter('customerAddress', $CustomerAddress)
                ->getQuery()
                ->execute();

            $Customer = $CustomerAddress->getCustomer();
            foreach ($Customer->getCustomerAddresses() as $customerAddress) {
                if ($customerAddress->getId() == $CustomerAddress->getId()) {
                    $Customer->removeCustomerAddress($customerAddress);
                    $CustomerAddress->setCustomer(null);
                    break;
                }
            }

            $em->persist($Customer);
            // Then remove the CustomerAddress
            $em->remove($CustomerAddress);

            $em->flush();
            $em->commit();
        } catch (\Exception $e) {
            $em->rollback();
            throw $e;
        }
    }
}
